import type { GuideV2CoursePackage } from "@/lib/types";

export const demoCoursePackage: GuideV2CoursePackage = {
  success: true,
  session_id: "competition-demo-stable",
  generated_at: 1_779_000_000,
  title: "机器学习基础个性化学习演示包",
  summary: "以“梯度下降”为主线，稳定展示学习画像、个性化路线、多智能体资源生成、智能辅导和学习效果评估闭环。",
  course_metadata: {
    course_name: "机器学习基础",
    target_learner: "高校人工智能专业低年级学生",
    weeks: 4,
  },
  capstone_project: {
    title: "用梯度下降训练一个小型回归模型",
    scenario: "学生需要解释损失函数、梯度方向、学习率和收敛现象，并完成一次可展示的小项目复盘。",
    deliverables: ["概念图解", "练习反馈", "学习报告", "项目说明"],
    steps: ["校准画像", "生成路线", "学习图解", "完成练习", "更新下一步"],
    focus_nodes: ["梯度下降", "损失函数", "模型评估"],
    estimated_minutes: 45,
  },
  rubric: [
    {
      criterion: "概念解释",
      weight: 30,
      excellent: "能用图解解释梯度、损失和参数更新的关系。",
      baseline: "能说出梯度下降的基本目标。",
    },
    {
      criterion: "练习表现",
      weight: 30,
      excellent: "能在练习中正确判断更新方向和学习率影响。",
      baseline: "能完成基础选择题。",
    },
    {
      criterion: "项目复盘",
      weight: 40,
      excellent: "能结合曲线和错误反馈解释下一步优化策略。",
      baseline: "能描述训练结果。",
    },
  ],
  portfolio: [
    {
      artifact_id: "visual-gradient-descent",
      task_id: "T3",
      task_title: "梯度下降图解",
      type: "visual",
      capability: "visualize",
      title: "梯度下降概念图",
      status: "ready",
      summary: "把损失曲线、梯度方向和参数更新关系画成结构图。",
    },
    {
      artifact_id: "audio-gradient-descent",
      task_id: "T4",
      task_title: "语音讲解",
      type: "audio",
      capability: "tts",
      title: "3 分钟语音讲解",
      status: "ready",
      summary: "把图解讲法转成可听的复习音频。",
    },
    {
      artifact_id: "quiz-gradient-descent",
      task_id: "T5",
      task_title: "短练习",
      type: "quiz",
      capability: "deep_question",
      title: "梯度下降即时练习",
      status: "ready",
      summary: "根据薄弱点生成 5 道可反馈练习。",
    },
    {
      artifact_id: "external-video-gradient-descent",
      task_id: "T4",
      task_title: "精选公开视频",
      type: "external_video",
      capability: "external_video_search",
      title: "公开视频补充讲解",
      status: "ready",
      summary: "按画像偏好筛选外部可观看课程视频。",
    },
  ],
  review_plan: [
    { node_id: "N2", title: "梯度方向", priority: "high", action: "先看图解，再做一组方向判断题。", mastery_score: 58 },
    { node_id: "N3", title: "学习率", priority: "medium", action: "对比过大和过小学习率的收敛曲线。", mastery_score: 72 },
    { node_id: "N4", title: "模型评估", priority: "medium", action: "用项目结果做一次复盘。", mastery_score: 76 },
  ],
  learning_style: {
    label: "图解 + 短练习驱动",
    summary: "学生更适合先建立直观图像，再用短题验证概念边界。",
    trend: "最近练习显示“梯度方向”和“学习率影响”仍需巩固。",
    demo_talking_point: "画像不是静态标签，而是直接改变资源形态和下一步任务。",
    path_effect: "系统优先安排图解、公开视频和短练习，而不是直接推长篇教材。",
    signals: [
      { label: "薄弱点", value: "梯度方向判断不稳" },
      { label: "偏好", value: "图解、公开视频、即时反馈" },
      { label: "时间", value: "每轮 10-15 分钟" },
    ],
  },
  demo_outline: ["画像校准", "路线生成", "资源 Studio", "练习反馈", "报告调整", "产出包"],
  demo_blueprint: {
    title: "7 分钟稳定演示路线",
    duration_minutes: 7,
    summary: "从学生目标进入，连续展示画像、路线、资源、练习、报告和比赛提交证据。",
    readiness_label: "可录屏",
    readiness_score: 92,
    learning_style: {
      label: "图解 + 短练习驱动",
      summary: "学生更适合先建立直观图像，再用短题验证概念边界。",
    },
    storyline: [
      {
        minute: "0:00-0:40",
        title: "评委模式开场",
        show: "打开 /demo，展示赛题五项证明和讯飞能力条。",
        talking_point: "这不是聊天机器人，而是一条完整学习闭环。",
        requirement: "赛题价值与技术融合",
      },
      {
        minute: "0:40-2:00",
        title: "画像与路径",
        show: "展示学习画像、知识地图和当前推荐任务。",
        talking_point: "画像信号直接影响路线和资源形态。",
        requirement: "对话式学习画像、个性化路径规划",
      },
      {
        minute: "2:00-4:20",
        title: "资源 Studio",
        show: "展示图解、语音、公开视频和练习资源。",
        talking_point: "多智能体把同一任务生成多模态学习材料。",
        requirement: "多智能体资源生成、智能辅导",
      },
      {
        minute: "4:20-6:20",
        title: "反馈与调整",
        show: "提交练习反馈，展示学习报告和路线调整前后。",
        talking_point: "评估不是分数，而是下一步处方。",
        requirement: "学习效果评估",
      },
      {
        minute: "6:20-7:00",
        title: "提交物收束",
        show: "回到课程产出包和提交清单。",
        talking_point: "PPT、视频、源码、文档都有对应页面证据。",
        requirement: "配套材料完整度",
      },
    ],
    fallbacks: ["现场生成慢时，使用稳定演示包中的图解、语音、练习和报告证据。"],
    judge_mapping: [
      { requirement: "学习画像", evidence: "画像信号与学习风格卡" },
      { requirement: "资源生成", evidence: "资源 Studio 与作品集" },
      { requirement: "路径规划", evidence: "闭环轨道与知识地铁图" },
      { requirement: "智能辅导", evidence: "多智能体接力剧场与多模态讲解" },
      { requirement: "学习评估", evidence: "路线调整前后与学习效果报告" },
    ],
  },
  demo_fallback_kit: {
    title: "稳定录屏兜底包",
    summary: "后端或模型波动时，仍可展示完整课程闭环和评分点证据。",
    persona: {
      name: "林同学",
      goal: "用 45 分钟补齐梯度下降直观理解",
      level: "机器学习入门",
      weak_points: ["梯度方向判断不稳", "学习率影响理解偏浅"],
      preferences: ["图解", "短练习", "公开视频"],
      story: "刚学完线性回归，希望能解释模型为什么会沿某个方向更新参数。",
    },
    assets: [
      {
        type: "visual",
        title: "梯度下降图解",
        status: "ready",
        show: "展示损失曲线和参数更新方向。",
        talking_point: "图解由画像和当前任务共同决定。",
      },
      {
        type: "quiz",
        title: "梯度方向短练习",
        status: "ready",
        show: "展示答题和即时反馈。",
        talking_point: "练习结果会回写学习效果。",
      },
      {
        type: "audio",
        title: "语音讲解",
        status: "seed",
        show: "展示 TTS 讲解入口。",
        talking_point: "同一知识点可转成可听资源。",
      },
    ],
    checklist: ["先开 /demo", "再进 /guide 课程产出包", "最后展示报告与提交清单"],
    fallback_script: ["如果现场生成变慢，说明这里使用稳定演示包，但系统真实链路仍由同一组件展示。"],
  },
  demo_seed_pack: {
    title: "机器学习基础稳定种子",
    scenario: "从梯度下降的卡点进入，完成图解、练习和报告更新。",
    persona: {
      name: "林同学",
      level: "入门",
      goal: "理解梯度下降",
      weak_points: ["梯度方向判断不稳"],
      preferences: ["图解", "练习", "语音"],
    },
    task_chain: [
      { task_id: "T1", title: "画像校准", stage: "profile", show: "确认薄弱点和偏好", sample_score: 70, status: "ready" },
      { task_id: "T2", title: "路线创建", stage: "route", show: "生成 4 个知识节点", sample_score: 74, status: "ready" },
      { task_id: "T3", title: "图解生成", stage: "visual", show: "生成梯度下降图解", resource_type: "visual", sample_score: 82, status: "ready" },
      { task_id: "T4", title: "短练习", stage: "quiz", show: "完成 5 道练习", resource_type: "quiz", sample_score: 68, status: "ready" },
      { task_id: "T5", title: "报告调整", stage: "report", show: "插入复测任务", sample_score: 76, status: "ready" },
    ],
    sample_artifacts: [
      { task_id: "T3", type: "visual", title: "梯度下降图解", preview: "损失曲线、梯度方向、参数更新", status: "ready" },
      { task_id: "T4", type: "quiz", title: "方向判断练习", preview: "5 题即时反馈", status: "ready" },
      { task_id: "T4", type: "external_video", title: "公开视频补充", preview: "按画像筛选", status: "seed" },
    ],
    rehearsal_notes: ["录屏时先说清学生目标，再让页面证据自己说话。"],
    report_anchor: {
      score: 76,
      readiness: "巩固中",
      action: "先复测梯度方向，再推进学习率。",
    },
  },
  demo_preflight: {
    title: "赛前一键检查",
    summary: "画像、路线、资源、练习、报告、提交清单均已有稳定证据。",
    status: "ready",
    score: 92,
    ready_count: 7,
    seed_count: 1,
    total_count: 8,
    next_action: "从 /demo 开始录制，再跳到 /guide 展示可操作链路。",
    primary_gap: null,
    checks: [
      { id: "profile", label: "学习画像", status: "ready", evidence: "林同学画像", action: "展示画像信号" },
      { id: "route", label: "个性化路线", status: "ready", evidence: "梯度下降路线", action: "展示知识地图" },
      { id: "resource", label: "多模态资源", status: "ready", evidence: "图解、语音、练习", action: "展示资源 Studio" },
      { id: "feedback", label: "练习反馈", status: "ready", evidence: "短练习结果", action: "展示反馈卡" },
      { id: "report", label: "学习评估", status: "ready", evidence: "路线调整前后", action: "展示报告" },
      { id: "iflytek", label: "讯飞工具链", status: "ready", evidence: "星火/Embedding/搜索/OCR/TTS", action: "展示能力条" },
    ],
  },
  presentation_outline: {
    title: "答辩 PPT 骨架",
    summary: "8 页以内，围绕价值、架构、核心功能、创新点和演示证据组织。",
    course_name: "机器学习基础",
    slide_count: 8,
    next_action: "优先截 /demo、资源 Studio、知识地铁图和证据瀑布。",
    slides: [
      { slide_no: 1, title: "项目定位", purpose: "一句话说明学习闭环", evidence: "/demo 驾驶舱截图", speaker_note: "先理解学生，再安排学习。" },
      { slide_no: 2, title: "技术架构", purpose: "说明多智能体和工具链", evidence: "接力剧场截图", speaker_note: "不同智能体负责不同阶段。" },
      { slide_no: 3, title: "核心功能", purpose: "展示画像、路径、资源、评估", evidence: "闭环轨道截图", speaker_note: "功能之间有数据回写。" },
      { slide_no: 4, title: "创新价值", purpose: "突出多模态和动态调整", evidence: "资源 Studio + Before/After", speaker_note: "不是只生成内容。" },
    ],
  },
  competition_submission: {
    title: "比赛提交清单",
    summary: "演示 PPT、源码、数据、部署配置、7 分钟视频和配套文档均有对应证据。",
    course_name: "机器学习基础",
    ready_count: 5,
    seed_count: 1,
    total_count: 6,
    next_action: "录制前按 /demo 的截图位生成 PPT 主图。",
    checklist: [
      { item: "演示 PPT", status: "seed", evidence: "已有 PPT 骨架和截图清单", action: "补最终截图" },
      { item: "多智能体源码", status: "ready", evidence: "ChatOrchestrator、ToolRegistry、CapabilityRegistry", action: "打包项目源码" },
      { item: "数据集与课程模板", status: "ready", evidence: "机器学习基础稳定课程包", action: "导出 demo seed" },
      { item: "模型部署配置", status: "ready", evidence: "设置页和讯飞能力条", action: "脱敏后提交" },
      { item: "演示视频", status: "seed", evidence: "7 分钟录屏路线", action: "按脚本录制" },
      { item: "配套文档", status: "ready", evidence: "计划书、runbook、AI Coding 说明", action: "统一格式" },
    ],
  },
  recording_script: {
    title: "7 分钟录屏脚本",
    summary: "用一条学生任务线展示所有评分点。",
    total_minutes: 7,
    next_action: "先录全流程，再剪掉等待时间。",
    segments: [
      { minute: "0:00", screen: "/demo", narration: "这里是评委模式，五项赛题要求都有证据入口。", backup: "若接口慢，使用稳定包截图。" },
      { minute: "1:00", screen: "/guide 路线", narration: "系统先读画像，再规划当前路径。", backup: "展示稳定课程模板。" },
      { minute: "3:00", screen: "资源 Studio", narration: "同一任务生成图解、语音、公开视频和练习。", backup: "使用已生成作品集。" },
      { minute: "5:00", screen: "学习报告", narration: "练习结果回写后，路线发生调整。", backup: "展示 Before/After 卡片。" },
      { minute: "6:30", screen: "提交清单", narration: "最后收束到 PPT、视频、源码和文档。", backup: "打开计划书完成记录。" },
    ],
  },
  ai_coding_statement: {
    title: "AI Coding 工具说明",
    summary: "AI Coding 用于辅助前端可视化、文档整理和测试补充，核心方案、赛题映射和最终审阅由参赛团队把关。",
    course_name: "机器学习基础",
    usage_scope: ["前端组件开发", "演示文档整理", "测试用例补充"],
    human_review: ["检查赛题要求映射", "审阅提交材料", "验证运行结果"],
    privacy_boundary: ["不提交 API Key", "不展示个人隐私数据", "演示数据使用稳定模板"],
    evidence: ["docs/competition-visualization-wow-plan.md", "web/src/pages/demo/DemoPage.tsx"],
    next_action: "提交时附上 AI Coding 说明。",
  },
  competition_alignment: {
    title: "赛题五项对齐证明",
    summary: "SparkWeave 用一个稳定课程包展示画像、资源、路径、辅导和评估全部闭环。",
    course_name: "机器学习基础",
    coverage_score: 92,
    ready_count: 5,
    seed_count: 0,
    total_count: 5,
    next_action: "按 /demo 的五项证明卡依次讲解。",
    primary_gap: null,
    proof_chain: [
      { label: "画像驱动", detail: "林同学的薄弱点和偏好决定资源形态。" },
      { label: "资源生成", detail: "图解、语音、练习和公开视频围绕同一任务生成。" },
      { label: "评估回写", detail: "练习反馈转成学习报告和下一步路线调整。" },
    ],
    requirements: [
      {
        id: "profile",
        requirement: "对话式学习画像自主构建",
        status: "ready",
        evidence: ["学习风格卡展示薄弱点、偏好和时间预算。"],
        demo_action: "展示画像驱动产出卡。",
      },
      {
        id: "resource",
        requirement: "多智能体协同的资源生成",
        status: "ready",
        evidence: ["资源作品集包含图解、语音、练习和公开视频。"],
        demo_action: "展示多智能体接力剧场和资源 Studio。",
      },
      {
        id: "path",
        requirement: "个性化学习路径规划和资源推送",
        status: "ready",
        evidence: ["闭环轨道和知识地铁图显示当前推荐任务。"],
        demo_action: "展示学习闭环轨道。",
      },
      {
        id: "tutor",
        requirement: "智能辅导",
        status: "ready",
        evidence: ["图解、语音和公开视频构成多模态答疑。"],
        demo_action: "展示多模态资源 Studio。",
      },
      {
        id: "assessment",
        requirement: "学习效果评估",
        status: "ready",
        evidence: ["路线调整前后卡展示新证据如何改变下一步。"],
        demo_action: "展示学习效果报告。",
      },
    ],
  },
  agent_collaboration_blueprint: {
    title: "多智能体协作蓝图",
    summary: "画像智能体、路径规划智能体、检索智能体、资源智能体和评估智能体共同完成当前学习任务。",
    course_name: "机器学习基础",
    current_task: "梯度下降直观理解",
    readiness: { label: "可展示", score: 90, detail: "角色、输入和产出均已可视化。" },
    roles: [
      { id: "profile", name: "画像智能体", responsibility: "读取目标、薄弱点和资源偏好。", uses: "学习证据", output: "画像信号", demo_action: "展示画像卡" },
      { id: "planner", name: "路径规划智能体", responsibility: "把目标拆成当前任务和下一步。", uses: "课程模板", output: "个性化路线", demo_action: "展示闭环轨道" },
      { id: "retriever", name: "知识检索智能体", responsibility: "补充课程资料和外部证据。", uses: "Embedding/RAG/ONE SEARCH", output: "证据片段", demo_action: "展示证据瀑布" },
      { id: "resource", name: "资源智能体", responsibility: "生成图解、语音、练习和视频建议。", uses: "星火/TTS", output: "多模态资源", demo_action: "展示资源 Studio" },
      { id: "evaluator", name: "评估智能体", responsibility: "根据练习反馈更新报告和路线。", uses: "学习行为数据", output: "下一步处方", demo_action: "展示 Before/After" },
    ],
    route: [
      { from: "学生目标", to: "画像智能体", message: "抽取薄弱点和偏好" },
      { from: "画像智能体", to: "路径规划智能体", message: "生成当前任务" },
      { from: "路径规划智能体", to: "资源智能体", message: "生产多模态资源" },
      { from: "资源智能体", to: "评估智能体", message: "接收练习反馈" },
      { from: "评估智能体", to: "下一步推荐", message: "动态调整路线" },
    ],
    recording_tip: "先用一句话说明角色分工，再让接力图展示过程。",
    next_action: "录屏时配合 Chat 接力剧场一起展示。",
  },
  defense_qa: {
    title: "答辩问答预案",
    summary: "围绕创新价值、讯飞工具链、落地可用性和评估闭环准备回答。",
    course_name: "机器学习基础",
    question_count: 4,
    top_risk: "评委可能追问是否只是普通聊天。",
    next_action: "回答时回到闭环轨道和路线调整前后截图。",
    questions: [
      {
        question: "和普通大模型问答有什么区别？",
        answer: "SparkWeave 把画像、路线、资源和评估串成闭环，练习反馈会改变下一步，而不是只输出一次回答。",
        evidence: "学习闭环轨道、路线调整前后。",
        demo_reference: "/demo",
      },
      {
        question: "讯飞能力具体用在哪里？",
        answer: "星火负责理解与生成，Embedding 支撑检索，ONE SEARCH 补外部资源，OCR 处理扫描资料，TTS 生成语音讲解。",
        evidence: "讯飞能力证明条。",
        demo_reference: "/demo",
      },
      {
        question: "多智能体是否真的可见？",
        answer: "前端展示接力剧场，能看到画像、规划、检索、资源和评估角色各自产出。",
        evidence: "多智能体接力剧场。",
        demo_reference: "/chat",
      },
    ],
  },
  learning_report: {
    overall_score: 76,
    readiness: "巩固中",
    progress: 68,
    behavior_summary: {
      event_count: 12,
      evidence_count: 9,
      resource_count: 4,
      quiz_attempt_count: 1,
      path_adjustment_count: 2,
      profile_update_count: 3,
      average_scored_activity: 76,
      type_counts: { profile: 3, resource: 4, quiz: 1, report: 2 },
    },
    behavior_tags: ["图解偏好", "短练习有效", "需复测梯度方向"],
    recent_timeline_events: [
      {
        id: "ev-quiz-1",
        type: "quiz_feedback",
        title: "梯度方向短练习完成",
        description: "5 题中 3 题正确，错题集中在参数更新方向。",
        score: 60,
        impact: "插入一轮梯度方向复测。",
        resource_type: "quiz",
      },
      {
        id: "ev-resource-1",
        type: "resource_view",
        title: "已查看梯度下降图解",
        description: "学生更容易通过曲线和箭头理解更新过程。",
        score: 82,
        resource_type: "visual",
      },
    ],
    effect_assessment: {
      score: 76,
      label: "巩固中",
      summary: "整体理解正在形成，但梯度方向仍需短复测；系统已把下一步从新内容推进调整为复测补强。",
      dimensions: [
        { id: "concept", label: "概念掌握", score: 72, status: "developing", evidence: "能解释目标，但方向题不稳定。" },
        { id: "practice", label: "练习表现", score: 60, status: "needs_support", evidence: "5 题中 3 题正确。" },
        { id: "resource", label: "资源吸收", score: 86, status: "stable", evidence: "图解资源反馈较好。" },
      ],
      strategy_adjustments: ["先复测梯度方向，再推进学习率。"],
      assessment_chain: [
        { label: "新证据", detail: "短练习暴露参数更新方向错误。" },
        { label: "系统判断", detail: "不是继续推新知识，而是先做一轮复测。" },
        { label: "下一步处方", detail: "生成 5 分钟方向判断练习，并回看图解。" },
      ],
    },
    demo_readiness: {
      score: 92,
      label: "可录屏",
      summary: "画像、资源、练习、报告和提交清单已成链。",
      checks: [
        { id: "profile", label: "画像", status: "ready", detail: "已具备" },
        { id: "resource", label: "资源", status: "ready", detail: "已具备" },
        { id: "report", label: "报告", status: "ready", detail: "已具备" },
      ],
      next_steps: ["开始 7 分钟演示录制。"],
    },
    mistake_summary: { cluster_count: 1, open_cluster_count: 1, low_score_evidence_count: 1, pending_retest_count: 1 },
    mistake_clusters: [
      { label: "梯度方向判断不稳", count: 2, severity: "high", suggested_action: "先做一轮方向判断复测。" },
    ],
    risks: ["如果现场生成变慢，使用稳定演示包。"],
    next_actions: ["先做梯度方向复测", "再推进学习率曲线对比"],
  },
  markdown: "# 机器学习基础个性化学习演示包\n\n稳定展示比赛五项要求。",
};
