"""Support modules for runtime configuration."""

from .provider_catalog import (
    DEPRECATED_SEARCH_PROVIDERS,
    EMBEDDING_PROVIDER_ALIASES,
    EMBEDDING_PROVIDERS,
    IFLYTEK_MAAS_CODING_ANTHROPIC_URL,
    IFLYTEK_MAAS_CODING_BASE_URL,
    IFLYTEK_MAAS_CODING_MODEL,
    IFLYTEK_SPARK_MODEL,
    IFLYTEK_SPARK_X2_BASE_URL,
    IFLYTEK_SPARK_X15_BASE_URL,
    NANOBOT_LLM_PROVIDERS,
    PROVIDER_ALIASES,
    PROVIDERS,
    SEARCH_ENV_FALLBACK,
    SUPPORTED_SEARCH_PROVIDERS,
    EmbeddingProviderSpec,
    ProviderSpec,
    canonical_provider_name,
    find_by_model,
    find_by_name,
    find_gateway,
    strip_provider_prefix,
)

__all__ = [
    "DEPRECATED_SEARCH_PROVIDERS",
    "EMBEDDING_PROVIDERS",
    "EMBEDDING_PROVIDER_ALIASES",
    "EmbeddingProviderSpec",
    "IFLYTEK_MAAS_CODING_ANTHROPIC_URL",
    "IFLYTEK_MAAS_CODING_BASE_URL",
    "IFLYTEK_MAAS_CODING_MODEL",
    "IFLYTEK_SPARK_MODEL",
    "IFLYTEK_SPARK_X15_BASE_URL",
    "IFLYTEK_SPARK_X2_BASE_URL",
    "NANOBOT_LLM_PROVIDERS",
    "PROVIDER_ALIASES",
    "PROVIDERS",
    "ProviderSpec",
    "SEARCH_ENV_FALLBACK",
    "SUPPORTED_SEARCH_PROVIDERS",
    "canonical_provider_name",
    "find_by_model",
    "find_by_name",
    "find_gateway",
    "strip_provider_prefix",
]
