#!/usr/bin/env python
"""Render a concise Markdown summary from a competition readiness JSON report."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


PROOF_POINTS = [
    (
        "多智能体协作",
        [
            "Runtime collaboration route: backend emitter",
            "Runtime collaboration route: frontend viewer",
            "Runtime collaboration route: test coverage",
        ],
        "协作路线、前端可视化和测试证据已成链。",
    ),
    (
        "公开视频学习闭环",
        [
            "External video loop: search service",
            "External video loop: chat handoff",
            "External video loop: viewer evidence",
            "External video loop: test coverage",
        ],
        "公开视频检索、聊天唤醒、前端学习卡和测试证据已覆盖。",
    ),
    (
        "学习效果评估",
        [
            "Effect assessment chain: backend report",
            "Effect assessment chain: frontend card",
            "Effect assessment chain: test coverage",
        ],
        "学习报告、前端卡片和测试证据已覆盖。",
    ),
    (
        "比赛证明链",
        [
            "Competition proof chain: backend package",
            "Competition proof chain: frontend card",
            "Competition proof chain: test coverage",
        ],
        "课程产出包、页面证据和测试证据已覆盖。",
    ),
    (
        "用户化体验护栏",
        [
            "User-facing diagnostics: settings status strip",
            "User-facing knowledge progress: milestone view",
            "User-facing chat trace: collaboration viewer",
        ],
        "设置报错、资料进度和对话轨迹都已避免暴露底层调试噪声。",
    ),
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("report", type=Path, help="Path to a JSON report generated by competition readiness checks.")
    parser.add_argument("--output", type=Path, help="Optional Markdown output path. Defaults to stdout.")
    args = parser.parse_args()

    report = json.loads(args.report.read_text(encoding="utf-8"))
    markdown = render_summary(report)

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(markdown, encoding="utf-8")
    else:
        print(markdown)
    return 0


def render_summary(report: dict[str, Any]) -> str:
    checks = [item for item in report.get("checks", []) if isinstance(item, dict)]
    failed = [item for item in checks if not item.get("ok")]
    ready_count = int(report.get("ready_count") or 0)
    total_count = int(report.get("total_count") or len(checks))
    failed_count = int(report.get("failed_count") or len(failed))
    success = bool(report.get("success"))
    status = "通过" if success else "需要处理"
    marker = "OK" if success else "FAIL"

    lines = [
        "# SparkWeave 赛前就绪摘要",
        "",
        f"**状态：{marker} {status}**",
        "",
        f"- 检查项：{ready_count}/{total_count} 通过",
        f"- 待处理：{failed_count}",
        f"- 结论：{report.get('summary') or '未提供摘要'}",
        "- 提交包：`dist/competition_package`",
        "- CI artifact：`competition-readiness`",
        "",
        "## 关键证据",
        "",
    ]

    names = {str(item.get("name") or "") for item in checks if item.get("ok")}
    for title, required, detail in PROOF_POINTS:
        point_status = "OK" if all(name in names for name in required) else "待补齐"
        lines.append(f"- {point_status} **{title}**：{detail}")

    if failed:
        lines.extend(["", "## 需要优先处理", ""])
        for item in failed[:10]:
            detail = str(item.get("detail") or "").strip()
            suffix = f"：{detail}" if detail else ""
            lines.append(f"- {item.get('name')}{suffix}")
    else:
        lines.extend(
            [
                "",
                "## 下一步",
                "",
                "- 可以进入录屏彩排或下载提交包做最终人工核对。",
                "- 正式提交前建议再运行 `sparkweave competition-preflight --with-build --report dist/competition-readiness.json`。",
            ]
        )

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
