/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        canvas: "#F7F8FA",
        surface: "#FBFCFD",
        ink: "#1A1A1A",
        charcoal: "#2F3136",
        slate: "#5D6470",
        steel: "#737985",
        stone: "#9AA0A8",
        line: "#E3E6EB",
        "line-soft": "#EDF0F4",
        "line-strong": "#C3C9D2",
        brand: {
          navy: "#0A1530",
          purple: {
            DEFAULT: "#6554B8",
            300: "#DED6FB",
            800: "#55469F",
          },
          teal: "#4B8B84",
          blue: "#3C78A8",
          red: "#E03131",
          orange: "#B65E2E",
          pink: "#A35B7F",
          yellow: "#E8CC54",
        },
        tint: {
          peach: "#FFF3EA",
          rose: "#FCEEF4",
          mint: "#EDF8F2",
          lavender: "#F3F4F7",
          sky: "#EEF6FC",
          yellow: "#FFF8DE",
          yellowBold: "#F4E7AA",
          cream: "#FAF7EF",
        },
        accent: {
          purple: {
            soft: "#F4F0FF",
            active: "#F7F4FF",
            line: "#DED6FB",
            marker: "#9F8FF0",
            ink: "#6554B8",
            strong: "#5E5390",
          },
          teal: {
            soft: "#EEF8F5",
            active: "#F2FAF7",
            line: "#CBE7E1",
            marker: "#63B8AA",
            ink: "#34776F",
            strong: "#2F6964",
          },
          blue: {
            soft: "#EEF6FC",
            active: "#F2F8FD",
            line: "#CFE5F6",
            marker: "#72AEE0",
            ink: "#2F75A8",
            strong: "#2E6F9D",
          },
          orange: {
            soft: "#FFF4EA",
            active: "#FFF7EF",
            line: "#F0D6BF",
            marker: "#DDA064",
            ink: "#A45D2C",
            strong: "#8D542D",
          },
          pink: {
            soft: "#FCEEF4",
            active: "#FFF5F9",
            line: "#EFD0DD",
            marker: "#D98AB1",
            ink: "#A35B7F",
            strong: "#935276",
          },
          yellow: {
            soft: "#FFFAF0",
            active: "#FFF4CE",
            line: "#EADFB7",
            marker: "#DFB962",
            ink: "#8A6422",
            strong: "#7B571D",
          },
        },
      },
      boxShadow: {
        panel: "0 18px 44px -32px rgba(15, 23, 42, 0.24), 0 1px 2px rgba(15, 23, 42, 0.04)",
        soft: "0 8px 20px -16px rgba(15, 23, 42, 0.18), 0 1px 2px rgba(15, 23, 42, 0.04)",
        mockup: "0 22px 50px -34px rgba(15, 23, 42, 0.26)",
      },
    },
  },
  plugins: [],
};
